/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Horse = IDL.Record({
  'odds' : IDL.Float64,
  'predictedProb' : IDL.Float64,
  'actualOutcome' : IDL.Bool,
});
export const Race = IDL.Record({
  'timestamp' : Time,
  'horses' : IDL.Vec(Horse),
});
export const OddsRange = IDL.Record({
  'max' : IDL.Float64,
  'min' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getROI' : IDL.Func([], [IDL.Float64], ['query']),
  'getRaceHistory' : IDL.Func([], [IDL.Vec(Race)], ['query']),
  'getTrustWeights' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(OddsRange, IDL.Float64))],
      ['query'],
    ),
  'getValueBets' : IDL.Func([IDL.Vec(Horse)], [IDL.Vec(Horse)], ['query']),
  'logRace' : IDL.Func([IDL.Vec(Horse)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Horse = IDL.Record({
    'odds' : IDL.Float64,
    'predictedProb' : IDL.Float64,
    'actualOutcome' : IDL.Bool,
  });
  const Race = IDL.Record({ 'timestamp' : Time, 'horses' : IDL.Vec(Horse) });
  const OddsRange = IDL.Record({ 'max' : IDL.Float64, 'min' : IDL.Float64 });
  
  return IDL.Service({
    'getROI' : IDL.Func([], [IDL.Float64], ['query']),
    'getRaceHistory' : IDL.Func([], [IDL.Vec(Race)], ['query']),
    'getTrustWeights' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(OddsRange, IDL.Float64))],
        ['query'],
      ),
    'getValueBets' : IDL.Func([IDL.Vec(Horse)], [IDL.Vec(Horse)], ['query']),
    'logRace' : IDL.Func([IDL.Vec(Horse)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };