/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Horse {
  'odds' : number,
  'predictedProb' : number,
  'actualOutcome' : boolean,
}
export interface OddsRange { 'max' : number, 'min' : number }
export interface Race { 'timestamp' : Time, 'horses' : Array<Horse> }
export type Time = bigint;
export interface _SERVICE {
  'getROI' : ActorMethod<[], number>,
  'getRaceHistory' : ActorMethod<[], Array<Race>>,
  'getTrustWeights' : ActorMethod<[], Array<[OddsRange, number]>>,
  'getValueBets' : ActorMethod<[Array<Horse>], Array<Horse>>,
  'logRace' : ActorMethod<[Array<Horse>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];